name: DEV.to Sync

on:
  push:
    branches: [master]

env:
  node-version: 14

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Get Yarn cache directory
        id: get-yarn-cache-dir
        run: echo "::set-output name=path::$(yarn cache dir)"
      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.get-yarn-cache-dir.outputs.path }}
          key: "${{ runner.os }}-node-${{ env.node-version }}-yarn-\
            ${{ hashFiles('**/yarn.lock') }}"
          restore-keys: |
            ${{ runner.os }}-node-${{ env.node-version }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn devto-sync
        env:
          DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤖 Sync DEV.to articles"
          token: ${{ secrets.ADMIN_GH_TOKEN }}
